### ISSUE TITLE
NoMethodError: undefined method `strip!' for nil:NilClass in JRuby

### ISSUE THREAD

**Issue by sapslaj** [layer8x/youtube-dl.rb#28]
```
1) Error:
YoutubeDL::Video::#formats#test_0003_should have a hash size of 4:
NoMethodError: undefined method `strip!' for nil:NilClass
    /home/travis/build/layer8x/youtube-dl.rb/lib/youtube-dl/output.rb:31:in `block in supported_formats'
    org/jruby/RubyArray.java:2300:in `map'
    /home/travis/build/layer8x/youtube-dl.rb/lib/youtube-dl/output.rb:30:in `supported_formats'
    /home/travis/build/layer8x/youtube-dl.rb/lib/youtube-dl/video.rb:48:in `formats'
    /home/travis/build/layer8x/youtube-dl.rb/test/youtube-dl/video_test.rb:71:in `block in (root)'
    org/jruby/RubyBasicObject.java:1633:in `instance_eval'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/spec.rb:183:in `block in before'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/test.rb:106:in `block in run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/test.rb:205:in `capture_exceptions'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/test.rb:105:in `block in run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/test.rb:256:in `time_it'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/test.rb:104:in `block in run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:334:in `on_signal'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/test.rb:276:in `with_info_handler'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest/test.rb:103:in `run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:781:in `run_one_method'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:308:in `run_one_method'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:296:in `block in run'
    org/jruby/RubyArray.java:1560:in `each'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:295:in `block in run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:334:in `on_signal'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:321:in `with_info_handler'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:294:in `run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:155:in `block in __run'
    org/jruby/RubyArray.java:2300:in `map'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:155:in `__run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:129:in `run'
    /home/travis/.rvm/gems/jruby-head/gems/minitest-5.8.3/lib/minitest.rb:56:in `block in autorun'
```
See the relevant [Travis Build](https://travis-ci.org/layer8x/youtube-dl.rb/jobs/91959278) for more info

**Comment by sapslaj** [comment]
v0.3 removes `#formats`. Closing.
