### ISSUE TITLE
youtube_dl is not part of the bundle. Add it to Gemfile. (Gem::LoadError)

### ISSUE THREAD

**Issue by birchlore** [layer8x/youtube-dl.rb#31]
When calling:

YoutubeDL.download "https://www.youtube.com/watch?v=gvdf5n-zI14", output: 'some_file.mp4'

I get this error:

/Users/jackson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:304:in `block in replace_gem': youtube_dl is not part of the bundle. Add it to Gemfile. (Gem::LoadError)

I previously had 'youtube_dl' in my gemfile, but replaced with 'youtube-dl.rb' and bundle install, bundle update.

Any idea why I'm getting this error message?

**Comment by sapslaj** [comment]
You have an outdated `Gemfile.lock`. You can just delete `Gemfile.lock` and regenerate using `bundle install`. Try that and see if that fixes anything.

**Comment by birchlore** [comment]
Hmm.. No luck. Here's the trace:

```
from /Users/jackson/.rbenv/versions/2.2.4/bin/youtube-dl:22:in `<main>'
from /Users/jackson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:91:in `run'
```

**Comment by sapslaj** [comment]
Ahh, I see the problem: `youtube_dl` is still installed, which causes a conflict with this gem when searching for a usable `youtube-dl` binary. See Issue #24.

**Comment by birchlore** [comment]
Oh, weird. Any idea on how to uninstall it? I thought removing it from gemfile was enough.. no?

**Comment by sapslaj** [comment]
`gem uninstall youtube_dl` or use a different gemset. 

This gem, `youtube-dl.rb`, searches for a `youtube-dl` binary in your PATH before falling back to the built in [youtube-dl](https://rg3.github.io/youtube-dl/). But the `youtube_dl` gem includes a binary named `youtube-dl` which from what I can tell is basically a really old version of [youtube-dl](https://rg3.github.io/youtube-dl/). When `youtube_dl` (the gem) is installed, rbenv will make a Ruby file called `youtube-dl` to correspond with the executable `youtube_dl` (the gem) includes, which basically figures out the Ruby environment you are using at the moment and redirects it to the appropriate directory. That's where the `Gem::LoadError` is coming from. 

It's really complicated, and it really sucks, but there's nothing I can really do about it.

**Comment by birchlore** [comment]
Ah, confusing but makes sense. Thanks for the explanation. Successfully removed youtube_dl, uninstalled youtube-dl.rb and re-installed from scratch.

Same use case, I'm getting this error:

Cocaine::CommandNotFoundError: Cocaine::CommandNotFoundError
from /Users/jackson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:82:in `run'

Sorry to keep beating at this, really appreciate your help.

**Comment by birchlore** [comment]
I've traced my error back to line 39 in youtube-dl.rb/lib/youtube-dl/video.rb

`set_information_from_json(YoutubeDL::Runner.new(url, @download_options).run)`

causes the error:

> Cocaine::CommandNotFoundError: Cocaine::CommandNotFoundError

**Comment by birchlore** [comment]
In support.rb line 30:

`line = Cocaine::CommandLine.new(executable_path, command)`

executable_path == "/Users/birchlore/.rbenv/shims/youtube-dl"

so my line.command looks like  `""/Users/birchlore/.rbenv/shims/youtube-dl --no-color --no-progress --print-json --format :format --prefer-ffmpeg --extract-audio --audio-format :audio_format \"https://www.youtube.com/watch?v=VA6kCaxaTlk\""`

and then line.run throws the error.

**Comment by birchlore** [comment]
Update. Issue resolved by running `brew install youtube-dl`. Not sure why I had to install it separately.

**Comment by sapslaj** [comment]
This is a very weird situation, but I applaud your persistence. I'll keep this issue open since it is technically a bug, and we might have to call in the rbenv guys to figure it out. 

Anyway, thanks for bringing my attention to an issue!
