### ISSUE TITLE
Cocaine::ExitStatusError

### ISSUE THREAD

**Issue by saigkill** [layer8x/youtube-dl.rb#62]
Hello layer8x,
i'm using your nice gem inside my own [gem](https://github.com/saigkill/youtube_dlhelper).
In my [lib/downloader.rb](https://github.com/saigkill/youtube_dlhelper/blob/master/lib/youtube_dlhelper/downloader.rb)  i'm using:

```
video = YoutubeDL.download(url)
video.filename # => "Adele - Hello-YQHsXMglC9A.f137.mp4"
video_with_title = YoutubeDL.download(url, extract_audio: true, audio_format: 'best', audio_quality: 0, output: '%(title)s.%(ext)s')
video_with_title.filename # => "Adele - Hello.mp4"
title = YoutubeDL::Runner.new(url, get_title: true).run
title # => "Adele - Hello"
filename = video_with_title.filename
```
My tests are located [there](https://github.com/saigkill/youtube_dlhelper/blob/master/lib/youtube_dlhelper/downloader.rb)

If i'm running the tests locally, i get:

> Finished in 29.98 seconds (files took 1.19 seconds to load)
> 14 examples, 0 failures

If i'm running it in [Travis](https://travis-ci.org/saigkill/youtube_dlhelper/jobs/284604450) i'm getting the error:

> 1) Downloader .get downloads a file from youtube
> Failure/Error: video = YoutubeDL.download(url)
> Cocaine::ExitStatusError:
>Command '/home/travis/build/saigkill/youtube_dlhelper/vendor/bundle/ruby/2.2.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl --no-color --no-progress --print-json "https://www.youtube.com/watch?v=UgdSarGbE0g"' returned 1. Expected 0
> Here is the command output: STDOUT:
> STDERR:
> WARNING: unable to extract uploader nickname
> ERROR: Signature extraction failed: Traceback (most recent call last):
> File "/home/travis/build/saigkill/youtube_dlhelper/vendor/bundle/ruby/2.2.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
> video_id, player_url, s
> File "/home/travis/build/saigkill/youtube_dlhelper/vendor/bundle/ruby/2.2.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 897, in _extract_signature_function
> raise ExtractorError('Cannot identify player %r' % player_url)
> ExtractorError: Cannot identify player u'/yts/jsbin/player-vfl1RKjMF/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vfl1RKjMF/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The differences:
Locally i'm running Ubuntu Zesty, Travis works with Trusty.

Both are using youtube-dl.rb-0.3.1.2016.09.11.1.

**Comment by aziflaj** [comment]
@saigkill facing the same issue. How did you solve this?

**Comment by realachiever** [comment]
@saigkill  I have the same issue.
If you found any solution, please let me know.
