### ISSUE TITLE
can download video

### ISSUE THREAD

**Issue by mm580486** [layer8x/youtube-dl.rb#64]
hi i receive this error after start download
```
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:91:in `run': Command '/usr/bin/youtube-dl --no-color --no-progress --print-json --skip-download "https://www.youtube.com/watch?v=fregObNcHC8"' returned 2. Expected 0 (Cocaine::ExitStatusError)
Here is the command output: STDOUT:



STDERR:

Usage: youtube-dl [options] url [url...]

youtube-dl: error: no such option: --no-color
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/lib/youtube-dl/runner.rb:62:in `run'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/lib/youtube-dl/video.rb:107:in `grab_information_without_download'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/lib/youtube-dl/video.rb:55:in `information'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/lib/youtube-dl/video.rb:65:in `method_missing'
	from bot.rb:70:in `block (2 levels) in <main>'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.4/lib/telegram/bot/client.rb:38:in `block in fetch_updates'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.4/lib/telegram/bot/client.rb:33:in `each'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.4/lib/telegram/bot/client.rb:33:in `fetch_updates'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.4/lib/telegram/bot/client.rb:25:in `listen'
	from bot.rb:37:in `block in <main>'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.4/lib/telegram/bot/client.rb:18:in `run'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.4/lib/telegram/bot/client.rb:8:in `run'
	from bot.rb:35:in `<main>'
r
```

**Comment by mm580486** [comment]
why i can download this videos https://www.youtube.com/watch?v=j9yBLt_2wj8 and https://www.youtube.com/watch?v=KEvtz5pUFxQ or https://www.youtube.com/watch?v=6a0K1sVrOr0 ?

but i cant download vevo and lyric video , whats happen ???
