### ISSUE TITLE
YoutubeDL::Options not handling hyphens in options keys correctly

### ISSUE THREAD

**Issue by SvHu** [layer8x/youtube-dl.rb#9]
Probably I'm doing something wrong but I tried to pass `--audio-format mp3`  option like this in`test.rb`:
```
options = {
  format: 'bestaudio',
  :"prefer-ffmpeg" => "true",
  :"extract-audio" => "true",
  :"audio-format" => "mp3"
}
YoutubeDL.download "https://www.youtube.com/watch?v=gvdf5n-zI14", options
```

I get an error:
```
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: invalid audio format specified
/home/sven/test_pleier/vendor/bundle/ruby/2.1.0/gems/cocaine-0.5.7/lib/cocaine/command_line.rb:92:in `run': Command '/usr/bin/youtube-dl --format format --prefer-ffmpeg --extract-audio --audio-format audio-format https://www.youtube.com/watch?v=gvdf5n-zI14' returned 2. Expected 0 (Cocaine::ExitStatusError)
Here is the command output:

        from /home/sven/test_pleier/vendor/bundle/ruby/2.1.0/gems/youtube-dl.rb-0.0.5/lib/youtube-dl/runner.rb:43:in `run'
        from /home/sven/test_pleier/vendor/bundle/ruby/2.1.0/gems/youtube-dl.rb-0.0.5/lib/youtube-dl.rb:18:in `block in download'
        from /home/sven/test_pleier/vendor/bundle/ruby/2.1.0/gems/youtube-dl.rb-0.0.5/lib/youtube-dl.rb:16:in `each'
        from /home/sven/test_pleier/vendor/bundle/ruby/2.1.0/gems/youtube-dl.rb-0.0.5/lib/youtube-dl.rb:16:in `download'
        from play.rb:17:in `<main>'
```

So I look further into `runner.rb` code and found out that if I replace `:#{key}` here with `#{option[key]}` then everything starts working
```
def options_to_commands
      commands = []
      options.each_paramized_key do |key, paramized_key|
        if options[key].to_s == 'true'
          commands.push "--#{paramized_key}"
        else
          commands.push "--#{paramized_key} :#{key}"
        end
      end
      commands.push url
      commands.join(' ')
    end
```
changed method:
```
def options_to_commands
      commands = []
      options.each_paramized_key do |key, paramized_key|
        if options[key].to_s == 'true'
          commands.push "--#{paramized_key}"
        else
          commands.push "--#{paramized_key} #{options[key]}"
        end
      end
      commands.push url
      commands.join(' ')
    end
```
Is it a bug or did I make mistake in passing the option in my `test.rb` file?

**Comment by SvHu** [comment]
My bad. Correct way to pass options is like this:
```
options = {
  format: 'bestaudio',
  prefer_ffmpeg: "true",
  extract_audio: "true",
  audio_format: "mp3"
}
YoutubeDL.download "https://www.youtube.com/watch?v=gvdf5n-zI14", options
```

**Comment by sapslaj** [comment]
Yep. `YoutubeDL::Options` handles converting symbol-to-key and underscore conversions for you. The only thing it doesn't handle that I don't particularly like is the value parameterization, but that's due to a [bug/feature in Cocaine](https://github.com/thoughtbot/cocaine/pull/78) that I nor thoughtbot has gotten around to dealing with. 

I do find it interesting that it blows up when supplied with a option key with a hyphen. I'll throw that on the backlog of things to take a closer look at. Thanks for bringing my attention to this issue!
